### ISSUE TITLE
leaderboard.models.alltime.AllianceLeaderboard.most_event_wins_2

### ISSUE THREAD

**Issue by jhtervay** [FRC-RS/FRS#1]
This function should return some form of iterable data type that contains:

* Pairs of 2 teams
* The number of events that pairing of teams has won on the same alliance

It is currently not functional (some pairings are not counted - I do not currently know why) and it is also grossly inefficient. Annotation via Django QuerySets would be an optimal fix.

You will notice that the pairing of teams 120 & 330 are not shown as winning 2 events together, despite actually having done so. This is just one example.

It *seems* (and I could be wrong) that it is not counting pairs from 3 way alliances that have won more than one event together (only 2 have: 120+330+2481 and 45+1024+1747).

**Comment by Matt529** [comment]
Is this still an issue?

**Comment by jhtervay** [comment]
No, leaderboard is deprecated and I've since had a few ideas on how to do the same thing but much faster.
