### ISSUE TITLE
Increase addmatches efficiency

### ISSUE THREAD

**Issue by jhtervay** [FRC-RS/FRS#3]
Currently the `addmatches` command (via `util/management/commands/addmatches.py`) is inefficient and slow. This is due to multiple reasons:
- Extra calls to `model.save()` throughout the function
- Writing a lot of JSON data (that we no longer need) in `TBAW.models.scoring.ScoringModel` - roughly 2.6KB per scoring model which likely is not necessary.

**Comment by Matt529** [comment]
Really could use a high-level description of what it is doing...

**Comment by jhtervay** [comment]
It's on my todo list.

**Comment by Matt529** [comment]
Implemented a bunch of optimizations and proper (hopefully) parallelization.

**Comment by Matt529** [comment]
The optimizations we have done so far are good enough for low-frequency tasks. See #19 for a low priority continuation.
